#!/bin/bash


sed -i 's/\r$//' "$0"

echo "[`date`]: ########## REMOVE EXISTING ZABBIX ##########"
systemctl stop zabbix_agentd zabbix-agent2 2>/dev/null
systemctl disable zabbix_agentd zabbix-agent2 2>/dev/null
ps -ef | grep zabbix | grep -v grep

# Break all the Zabbix-related links and remove old files
find /usr /etc /run -type l -name "*zabbix*" -exec unlink {} \;

rpm_name=$(rpm -qa | grep -i 'zabbix-agent2')
if [[ -n "$rpm_name" ]]; then
    rpm -e "$rpm_name"
fi

rpm_zs=$(rpm -qa | grep -i 'zabbix-sender')
if [[ -n "$rpm_zs" ]]; then
    rpm -e "$rpm_zs"
fi

echo "[`date`]: ########## INSTALL NEW ZABBIX ##########"
OS_VERSION=$(rpm -E %{rhel})

case $OS_VERSION in
    7)
        echo "OS Version is $OS_VERSION"
        yum install -y pcre2
        rpm -ivh zabbix-agent2-7.0.5-release1.el7.x86_64.rpm || { echo "Installation failed"; exit 1; }
        rpm -ivh zabbix-sender-7.0.5-release1.el7.x86_64.rpm
        systemctl enable zabbix-agent2
        ;;
    8)
        echo "OS Version is $OS_VERSION"
        yum install -y pcre2
        rpm -ivh zabbix-agent2-7.0.5-release1.el8.x86_64.rpm || { echo "Installation failed"; exit 1; }
        rpm -ivh zabbix-sender-7.0.5-release1.el8.x86_64.rpm
        systemctl enable zabbix-agent2
        ;;
    9)
        echo "OS Version is $OS_VERSION"
        rpm -ivh zabbix-agent2-7.0.5-release1.el9.x86_64.rpm || { echo "Installation failed"; exit 1; }
        rpm -ivh zabbix-sender-7.0.5-release1.el9.x86_64.rpm
        systemctl enable zabbix-agent2
        ;;
    *)
        echo "Unsupported RHEL version"
        exit 1
        ;;
esac

# Update the service file for Zabbix Agent 2
if [[ -f /usr/lib/systemd/system/zabbix-agent2.service ]]; then
    sed -i "s/User=zabbix/User=root/g;s/Group=zabbix/Group=root/g" /usr/lib/systemd/system/zabbix-agent2.service
fi
systemctl daemon-reload

# Update Zabbix configuration
if [[ -f /etc/zabbix/zabbix_agent2.conf ]]; then
    echo "[`date`]: Existing config."
    egrep -v "^$|^#" /etc/zabbix/zabbix_agent2.conf

    sed -i "s/^Hostname.*/Hostname=`hostname`/g;
            s/^Server=.*/Server=/g;
            s/^ServerActive=.*/ServerActive=/g" /etc/zabbix/zabbix_agent2.conf

    sed -i "s/^# UnsafeUserParameters=0/UnsafeUserParameters=1/g;
            s/# UserParameter=/UserParameter=usercmd[*],\$1/g" /etc/zabbix/zabbix_agent2.conf

    echo "AllowKey=system.run[*]" >> /etc/zabbix/zabbix_agent2.conf

    echo "[`date`]: Updated config."
    egrep -v "^$|^#" /etc/zabbix/zabbix_agent2.conf
fi

# Restart Zabbix Agent
if systemctl list-unit-files | grep -q zabbix-agent2; then
    systemctl restart zabbix-agent2
else
    systemctl restart zabbix-agent2
fi

echo "[`date`]: Zabbix Agent setup complete."














DR_agent_upgrade_v1.sh: line 2: $'\r': command not found
DR_agent_upgrade_v1.sh: line 3: $'\r': command not found
: No such file or directorygrade_v1.sh
DR_agent_upgrade_v1.sh: line 5: $'\r': command not found
[Mon Feb 10 22:29:26 +13 2025]: ########## REMOVE EXISTING ZABBIX ##########
root      166299  166269  0 22:29 pts/0    00:00:00 grep zabbix
DR_agent_upgrade_v1.sh: line 10: $'\r': command not found
DR_agent_upgrade_v1.sh: line 13: $'\r': command not found
DR_agent_upgrade_v1.sh: line 27: syntax error near unexpected token `$'in\r''
'R_agent_upgrade_v1.sh: line 27: `case $OS_VERSION in
